receivers: ${file:/etc/otel-collector-config/receivers.yaml}

processors:
  batch/local:
    send_batch_size: 4000
    send_batch_max_size: 5000
    timeout: 1s

exporters:
  ## Set generic otel collector as OTLP endpoint for bigip-scraper to send metrics to
  otlp/otel-prometheus-exporter:
    endpoint: otel-collector-prom-exporter:4317
    tls:
      insecure: true
  debug/bigip:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 200

service:
  # Changed in upstream otel collector, default only responds on localhost
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
  pipelines: ${file:/etc/otel-collector-config/pipelines.yaml}
